name: lotuserp_pdv
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  flutter_vector_icons: ^2.0.0
  sidebarx: ^0.16.3
  flutter_simple_bluetooth_printer: ^0.1.4

  
dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  